# Generated by Django 3.0 on 2019-12-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0003_auto_20191219_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='ns101',
            name='roll',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
